### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by jforaker** [MattFoley/react-native-paypal#1]
plans?

**Comment by chagasaway** [comment]
+1

**Comment by amiuhle** [comment]
I started merging this repository into vizir/react-native-paypal#1

@MattFoley Is that okay with you (there's no license in the repo)?

**Comment by MattFoley** [comment]
@amiuhle Sure go to town, added a license for you.

@jforaker @chagasaway Just an FYI, I won't be adding Android support to this repo anytime soon. Maybe sometime this summer? It's just not a priority for me, and I don't work on Android very often. If you guys want to build android support into this repo, I'd be happy to accept, otherwise it looks like that other repo linked above may be better. (This was really just a learning project for RN for me.)

**Comment by MattFoley** [comment]
Just an update, the other repository linked above in this issue is now dead, so we will be moving Android support here in soon.
