### ISSUE TITLE
Unknown argument Type 'PayPalEnviroment' in method - [MFLReactNativePayPal]

### ISSUE THREAD

**Issue by deresegetachew** [MattFoley/react-native-paypal#2]
I am getting the above error ; i have attached the screen shot for the error

<img width="357" alt="screen shot 2016-01-16 at 9 04 49 am" src="https://cloud.githubusercontent.com/assets/2713659/12370831/675b86ba-bc30-11e5-93e6-d091ca4ca635.png">

**Comment by micheledibenedetto7** [comment]
Hi, I am getting the same error, the same screen. How did you solve this? Thanks in advance.

**Comment by deresegetachew** [comment]
:) i am waiting for @MattFoley to rescue me ; i am trying to use BrainTree while waiting for him to respond to this; the problem is i have never touched objective C and couldn't help out myself much; react-native-braintree is also another alternative. if you decide to use that too we can share some learning curves from that too over email

**Comment by micheledibenedetto7** [comment]
i have never touched objective C too :( and i am really undecided for the moment cause of i have to choose between react native and ionic + cordova. I like the idea to use native interface for my app with react native but it seems there are stile few alternatives when it comes to plug in a feature like simple paypal payment in this case and in this specific case there is not even an android version. I guess i will take some time to think about it. thank you very much.

**Comment by deresegetachew** [comment]
https://github.com/Vizir/react-native-paypal  thats for android

this is my skype id : if you need more info derese.getachew
react is the way bro!

**Comment by micheledibenedetto7** [comment]
thanks man, i will surely give it a try!

**Comment by micheledibenedetto7** [comment]
just for test purpose i solved the first problem by doing this in the MFLReactNativePaypal.m from line 28 to 40:

RCT_EXPORT_METHOD(initializePaypalEnvironment:(NSString *)environment
                  forClientId:(NSString *)clientId )
{
  dispatch_async(dispatch_get_main_queue(), ^{
    // NSString *envString = [self stringFromEnvironmentEnum:environment];

```
//[PayPalMobile initializeWithClientIdsForEnvironments:@{envString : clientId}];
// [PayPalMobile preconnectWithEnvironment:envString];

[PayPalMobile initializeWithClientIdsForEnvironments:@{environment : clientId}];
[PayPalMobile preconnectWithEnvironment:environment];
```

  });
}

then in my index.ios.js file i did this at line 21:

// note that as the first argument i pass a string instead of an int value
MFLReactNativePayPal.initializePaypalEnvironment('0','...my_client_id...');

now the problem is that if i try to choose credit card for payment instead of my paypal account this error happens:

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Application tried to present a nil modal view controller on target <PayPalPaymentViewController: 0x7d970400
Environment: 0
languageOrLocale: (null)


i try with sandox and production client_id and email too of a business account so i can't understand why this happens? is it an account configuration problem or is it just the wrapper that does not work? any idea?

**Comment by MattFoley** [comment]
I'm sorry, just saw these, let me take a look this morning.

**Comment by MattFoley** [comment]
@troublesome80 I'm pushing an update shortly that will fix your environment work arounds. (I wrote this for RN 0.5, so it's very out of date.) For your crash, you'll see in my update PayPal has moved to packaging CardIO separately, so you'll also need to include three new .a files and related header files in your project.
<img width="243" alt="screen shot 2016-01-19 at 12 34 20 pm" src="https://cloud.githubusercontent.com/assets/1182042/12431210/fbfc01d0-bea8-11e5-8510-a65f2635e162.png">

**Comment by MattFoley** [comment]
@derese Fix coming now for your RCTConvert issue.

**Comment by MattFoley** [comment]
This commit fixes your issue: https://github.com/MattFoley/react-native-paypal/commit/e50c764667db5bb3dd60d7c19f81e480a8bc363e

I'm publishing 0.0.2 to NPM right now.

**Comment by micheledibenedetto7** [comment]
great! thanks.

**Comment by MattFoley** [comment]
Having some strange issues with npm publish, so I guess I won't be pushing an update to npm today! The head of master here should be stable though.

**Comment by micheledibenedetto7** [comment]
i tested it with the fixes and can confirm that all works great. unfortunately using direct credit card payment works only in sandbox and not live but that is a country restriction for the paypal REST API. bye

**Comment by deresegetachew** [comment]
thank you @MattFoley
